Repository SVCE-ACM/A-December-of-Algorithms-2019, pull requests merged in 2019-12, with the labels that each got.

#11 Merge for December 6, 7, 8
  README.md
Labels: Merge

#9 December 9 - One to One
  README.md
Labels: New Problem Statement

#14 Merge for December 9
  README.md
Labels: Merge

#16 Created Day 10 Question (Count The Cookies)
  README.md
Labels: New Problem Statement

#17 Merge for December 10
  README.md
Labels: Merge

#29 Added December 12 question
  README.md
  src/res/JaSON.json
Labels: New Problem Statement

#30 Added december 13,14 and 15 question
  README.md
Labels: New Problem Statement

#32 Added december 16 question
  README.md
Labels: Merge, New Problem Statement

#35 December-17
  README.md
  src/assets/December-17 Subway Surfers.png
Labels: New Problem Statement

#36 Merge Problem for December 17
  README.md
  src/assets/December-17 Subway Surfers.png
Labels: Merge

#40 DOC 19
  README.md
  src/assets/Convexhull.jpg
Labels: Merge, New Problem Statement

#45 Add Question for Dec 22
  README.md
Labels: New Problem Statement

#46 Update README.md
  README.md
Labels: New Problem Statement

#47 Added december 24 question
  README.md
Labels: Merge, New Problem Statement

#48 Dhirajv2000 patch 2
  README.md
Labels: New Problem Statement

#51 Add question for 27th December
  README.md
Labels: Merge, New Problem Statement

#52 Added December 28 question
  README.md
Labels: Merge, New Problem Statement

#53 Interim
  README.md
Labels: Merge

#56 Added December 31 question
  README.md
  src/assets/build_city.jpg
  src/res/build_city_csv.csv
Labels: Merge, New Problem Statement
